Development
geraldgsh/enumerable_methods pull request #2
Opened 2019-10-13 17:06 UTC by geraldgsh

- Completed Enumerable module with methods
- Ready for TSE review

2019-10-14 17:55 UTC, samgaco requested changes
Hi @geraldgsh :high_brightness: 

I leave some comments on what functionalities your methods are lacking. You can find a reference of how they are expected to work [here](https://ruby-doc.org/core-2.6.4/Enumerable.html).

Please, work on these required comments and submit them back for another code review once you are done.

------------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-10-14 17:55 UTC, samgaco commented on main.rb
> +        return false if yield(self[i]) == false || yield(self[i]).nil?
- [ ] my_all? when no block or argument is given returns true when none of the collection members are false or nil
- [ ] my_all? when a class is passed as an argument returns true if all of the collection is a member of such class
- [ ] my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-10-14 17:55 UTC, samgaco commented on main.rb
> +        return true if yield(f)
- [ ] my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
- [ ] my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class
- [ ] my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2019-10-14 17:55 UTC, samgaco commented on main.rb
> +      while self[i]
- [ ] my_none? when no block or argument is given returns true only if none of the collection members is true
- [ ] my_none? when a class is passed as an argument returns true if none of the collection is a member of such class
- [ ] my_none? when a Regex is passed as an argument returns true only if none of the collection matches the Regex
- [ ] my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-10-14 17:55 UTC, samgaco commented on main.rb
> +      count += 1
- [ ] my_count counts the number of items in enum that are equal to item if an argument is given
- [ ] my_count counts the number of elements yielding a true value if a block is given

2019-10-14 17:55 UTC, samgaco commented on main.rb
> +      my_each do |i|
- [ ] my_map returns a new array with the results of running block once for every element in enum.
- [ ] my_map returns an Enumerator if no block is given

2019-10-14 17:55 UTC, samgaco commented on main.rb
> +      mem = if mem.nil?
- [ ] my_inject combines all elements of enum by applying a binary operation, specified by a block
- [ ] my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method

2019-10-16 13:56 UTC, geraldgsh commented
@samgaco noted. Changes have been made and a separate code review request has been made.

2019-10-16 18:52 UTC, whiz25 approved these changes
## Awesome :clap: 
You have implemented all the suggested features. You can merge.

#### Martin Afani

2019-10-16 19:46 UTC, geraldgsh commented
> ## Awesome 👏
> You have implemented all the suggested features. You can merge.
> 
> #### Martin Afani

Thanks @whiz25 for taking the time to go thru my work. Have a blessed day ahead of you.

2019-10-16 19:47 UTC, merged